2020-02-14 01:15:59.726 [error] <0.718.0>@Elixir.DBConnection.ConnectionPool:handle_info:34 gen_server <0.718.0> terminated with reason: no function clause matching 'Elixir.DBConnection.ConnectionPool':handle_info({'DOWN',#Ref<0.2171341305.4082368520.114050>,process,<0.721.0>,shutdown}, {ready,#Ref<0.2171341305.4082499592.114020>,#{delay => 0,idle => #Ref<0.2171341305.4082368519.114029>,...}}) line 34
2020-02-14 01:49:43.180 [error] <0.601.0> CRASH REPORT Process <0.601.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.180 [error] <0.602.0> CRASH REPORT Process <0.602.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.184 [error] <0.601.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.600.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.184 [error] <0.602.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.599.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.211 [error] <0.606.0> CRASH REPORT Process <0.606.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.211 [error] <0.606.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.605.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.212 [error] <0.607.0> CRASH REPORT Process <0.607.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:49:43.213 [error] <0.607.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.604.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:29.994 [error] <0.612.0> CRASH REPORT Process <0.612.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:29.995 [error] <0.612.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.609.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:29.996 [error] <0.611.0> CRASH REPORT Process <0.611.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:29.997 [error] <0.611.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.610.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:30.118 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:30.119 [error] <0.617.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:30.119 [error] <0.618.0> CRASH REPORT Process <0.618.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:30.119 [error] <0.618.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.615.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.427 [error] <0.621.0> CRASH REPORT Process <0.621.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.427 [error] <0.621.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.620.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.432 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.432 [error] <0.624.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.623.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.554 [error] <0.629.0> CRASH REPORT Process <0.629.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.554 [error] <0.629.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.627.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.555 [error] <0.628.0> CRASH REPORT Process <0.628.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:33.556 [error] <0.628.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.626.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.572 [error] <0.646.0> CRASH REPORT Process <0.646.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.572 [error] <0.646.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.645.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.573 [error] <0.647.0> CRASH REPORT Process <0.647.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.574 [error] <0.647.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.644.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.709 [error] <0.651.0> CRASH REPORT Process <0.651.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.709 [error] <0.651.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.649.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.715 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:51:37.715 [error] <0.652.0> Cowboy stream 1 with ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' and connection process <0.650.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.Ledger.Worker',reason => nil},[{'Elixir.Ledger.Worker',publish,[<<"{\"user_id\":\"xyz\",\"event\":\"sent_a_message\"}">>],[]},{'Elixir.LedgerWeb.QueueController',index,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,6}]},{'Elixir.LedgerWeb.QueueController',action,2,[{file,"lib/ledger_web/controllers/queue_controller.ex"},{line,1}]},{'Elixir.LedgerWeb.QueueController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-02-14 01:55:34.114 [error] <0.492.0> Failed to start Ranch listener 'Elixir.LedgerWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-02-14 01:55:45.305 [error] <0.381.0> Supervisor 'Elixir.Ledger.Supervisor' had child 'Elixir.Ledger.Queue.Worker' started with 'Elixir.Ledger.Queue.Worker':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Ledger.Queue.Worker',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[...]},...]}} in context start_error
2020-02-14 01:56:37.750 [error] <0.381.0> Supervisor 'Elixir.Ledger.Supervisor' had child 'Elixir.Ledger.Queue.Worker' started with 'Elixir.Ledger.Queue.Worker':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Ledger.Queue.Worker',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[...]},...]}} in context start_error
2020-02-14 01:57:15.297 [error] <0.381.0> Supervisor 'Elixir.Ledger.Supervisor' had child 'Elixir.Ledger.Queue.Worker' started with 'Elixir.Ledger.Queue.Worker':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Ledger.Queue.Worker',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[...]},...]}} in context start_error
